### ISSUE TITLE
Plugin crashes Homebridge on launch

### ISSUE THREAD

**Issue by oogje** [sean9keenan/homebridge-bigAssFans#38]
Hello,

My config is 
        {
            "accessory": "BigAssFan",
            "name": "Big Fan",
            "fan_name": "Big Fan",
            "fan_id": "b8:f0:09:ac:bd:b8"
        }

The log is:

[4/11/2021, 11:10:43 AM] [Big Fan] Initializing BigAssFan accessory...
[4/11/2021, 11:10:43 AM] [Big Fan] No light exists for: Big Fan Fan Light
[4/11/2021, 11:10:43 AM] TypeError: existingAccessory.getService is not a function
    at new BigAssFanAccessory (/usr/local/lib/node_modules/@miblanchard/homebridge-big-ass-fans/index.js:277:44)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:350:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:12)
[4/11/2021, 11:10:43 AM] Got SIGTERM, shutting down Homebridge...

I should mention that I assumed the MAC address was the fan_id and the name I assigned the fan was the fan_name because getFanInfo.js from theBigAssFansAPI did not output anything.  Will open an issue in the theBigAssFansAPI about that.

Thank you for your efforts.

- brian

edited to add: Homebridge v1.3.4

**Comment by Emotive9** [comment]
Same problem here, although I have no config set since I have 4 fans. Oddly enough the plugin still works on HOOBs.

**Comment by TopBanana123** [comment]
Same issue here, exact same error
